#ifndef DEVICE_ADDRESS_H_
#define DEVICE_ADDRESS_H_

#define SRC_TEMP_ADDR 0x10
#define SRC_HUMID_ADDR 0x20
#define SRC_SOIL_ADDR 0X30
#define SRC_CAMERA_ADDR 0x40
#define SRC_MQTT_ADDR 0x50

#define DST_TEMP_ADDR 0x01
#define DST_HUMID_ADDR 0x02
#define DST_SOIL_ADDR 0x03
#define DST_CAMERA_ADDR 0x04
#define DST_MQTT_ADDR 0x05

#endif